### ISSUE TITLE
How far is this plugin from being available as a general release?

### ISSUE THREAD

**Issue by wolfgangkoch** [rabbitmq/rabbitmq-auth-backend-uaa#11]
Dear @hairyhum @michaelklishin et al,
Thank you for your work on this plugin. We are looking exactly for something like this for our setup where the UAA is the center of authentication and authorization.

How far do you think is this plugin from being available for general usage?

Many regards,
Wolfgang

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
Possibly [infinitely far](https://groups.google.com/d/msg/rabbitmq-users/Q0DwZyzZrC8/VEjDkTDFAgAJ). We have no plan of abandoning attempts to finish it but also depend on decision makers outside of our team on what the scope and expected behaviour should be :/

**Comment by michaelklishin** [comment]
@wolfgangkoch that said, we would really value feedback from someone actually trying to adopt this plugin (after 3.7.0 is out — you can develop against 3.7.0 snapshots or RC1 since we'd love more feedback on those versions in general). The more evidence that the current strategy of scope-to-RabbitMQ permission mapping is sane and flexible there is, the easier it is for us to make our case to other teams that will have to rely on this plugin.

**Comment by michaelklishin** [comment]
@wolfgangkoch …so any feedback you have is welcomed on rabbitmq-users. See #10 for a good starting point (currently undergoing QA).

**Comment by wolfgangkoch** [comment]
Thanks for your fast feedback, Michael.
"Possibly infinitely far" sounds a bit discouraging. We would gladly like to provide feedback (and use the plug-in) if there is some hope of it reaching release status in the coming days.

**Comment by michaelklishin** [comment]
@wolfgangkoch it's a chicken-and-egg problem for us: we can't release something that we are not sure makes sense/useful to certain specific teams but if we don't do it, nobody feels confident about giving it a real shot…

**Comment by wolfgangkoch** [comment]
@michaelklishin As long as it does not reduce the security level of rabbit MQ and the applications connected to it (including the oAuth mechanism), I don't see why, in my naive understanding, we could not start talking about release candidates for this plug-in.
We ourselves were thinking of ideas including passing the token as part of the message header which would be validated by resource server apps via the UAA.

**Comment by michaelklishin** [comment]
@wolfgangkoch we [mention the reason](https://groups.google.com/d/msg/rabbitmq-users/Q0DwZyzZrC8/VEjDkTDFAgAJ) in a recent rabbitmq-users thread.

**Comment by michaelklishin** [comment]
@wolfgangkoch I’m inclined to say “teams that do not participate in plugin design discussions only have themselves to blame when something isn’t up to their liking” at this point. Maybe after we finish #10 we can produce a milestone of this plugin and see how it goes.

**Comment by wolfgangkoch** [comment]
@michaelklishin  "Maybe after we finish #10 we can produce a milestone of this plugin and see how it goes." :+1: Now we are talking!
Having a micro-service/REST based architecture secured by oAuth2.0 without important connectivity components like RabbitMQ not taking part in it seems like an incomplete solution. You guys do UAA/CF as well as RabbitMQ, I am sure that the approaches you take cannot be to far from the ideal one. We already have the LDAP plugin, the time is ripe for the oAuth2.0 plugin.

**Comment by michaelklishin** [comment]
We have merged #10 but also discovered that our UAA JWT library has a dependency that swallows exceptions, making it really painful to debug key signature verification failures. We should fix that before releasing a milestone. The issue is #12.

**Comment by wolfgangkoch** [comment]
Cool. Meanwhile we are currently testing the plug-in in-house. We will provide you some feedback soon. Thanks for your help.
