### ISSUE TITLE
Why loading key into Rabbit; why not call UAA to validate the token?

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-auth-backend-uaa#14]
I wonder why you decided to let the plug-in decode the token rathe than call the user_info endpoint in UAA? I foresee lots of issues exposing and maintaining the UAA keys outside of PCF.

**Comment by michaelklishin** [comment]
1. This plugin is an experiment with very little actual feedback from CF developers and users. Yes, after a few years of discussions of what OAuth 2 support might look like.
2. CredHub did not exist when this project was started. Certificate management is still not a solved problem in CF even today, so we are not sure how many alternatives we have.
3. We do not expect this plugin to be used "outside of PCF" but it might be, at which point e.g. CredHub may or may not be available.
4. Under load such plugins are known to take down external services such LDAP servers and UAA will be no exception. https://github.com/rabbitmq/rabbitmq-auth-backend-cache helps with that but the idea of caching credentials seems wrong to some.

This decision is not set in stone but we'd like to finish a version of this plugin around the time 3.7.0 ships even if it's imperfect. There have been too many fruitless debates about what it might looks like but nothing the users can actually consider because vaporware is not something that can be deployed.

As always , discussions are welcome on rabbitmq-users.
