### ISSUE TITLE
will oauth be supported also for the management ui?

### ISSUE THREAD

**Issue by chicco785** [rabbitmq/rabbitmq-auth-backend-uaa#22]
I wonder if the oauth support is going to work also for the ui

thx

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Yes, it will use a different authorization flow, however. We will file an issue with details once we get back to working on OAuth 2 for 3.8.
