### ISSUE TITLE
How to using this plugin

### ISSUE THREAD

**Issue by tuanpt89** [rabbitmq/rabbitmq-auth-backend-uaa#26]
Hi,
Can anyone tell me the steps to steps to use this plugin?
I imagine the need to implement steps like this model is correct:
[https://pasteboard.co/IemRp7X.png](url)

Example: 
+ How to build and enable this plugin? I ran this command but failure:

> #rabbitmq-plugins enable rabbitmq_auth_backend_oauth2
> Enabling plugins on node rabbit@rabbitmq2:
> rabbitmq_auth_backend_oauth2
> {:plugins_not_found, [:rabbitmq_auth_backend_oauth2]}

+ When I ran: #make run-broker RABBITMQ_CONFIG_FILE=demo/symmetric_keys/rabbitmq
It's required elixir and then elixir required other services (ex: dialyzer) that I couldn't install (I'm using Centos 7, Rabbitmqserver 3.7 and Erlang 21)

+ How to config with new format in rabbitmq configuration file with structured Key = Value
Thank you very much!
![rabbit-oauth2](https://user-images.githubusercontent.com/27726563/57581221-7c63fc80-74de-11e9-913a-5fbf6e83e2b3.png)
![rabbit-oauth2](https://user-images.githubusercontent.com/27726563/57583780-33bc3b80-74fe-11e9-9aba-494e646cdab3.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin will ship with RabbitMQ 3.8.

To build it and use e.g. with `3.8.0-beta.4`, use `gmake dist`. Elixir is a [server compile time dependency](https://www.rabbitmq.com/build-server.html), so if you cannot install it (there's a precompiled build from the Elixir team available on GitHub), you cannot build RabbitMQ from source, you cannot build this plugin from source either.

**Comment by michaelklishin** [comment]
Here's a binary build with one dependency specific to this plugin: [rabbitmq_auth_backend_oauth2-f48bf98.zip](https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2/files/3170387/rabbitmq_auth_backend_oauth2-f48bf98.zip).
