### ISSUE TITLE
client

### ISSUE THREAD

**Issue by taijitao** [rabbitmq/rabbitmq-auth-backend-uaa#35]
Hi,
it's a question not a issue.
i got a RPT token (JWT format) from keycloak since I want to use keycloak as SSO.
Rabbitmq version is 3.7.15, the plugin is rabbitmq_auth_backend_oauth2-f48bf98.ez.
i used python pika library to send request:

```
#!/usr/bin/env python
import pika
token=b'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJnRmZTRi1oSE40SHpWWDVUUHczeGQ5WHp1Nk03Sm1xbUlLWmc2UUZvbHNNIn0.eyJqdGkiOiJmZjRkN2M4ZS1kNTg4LTQ4YmMtYWI4Zi
01NjdjN2U5YWJiNTYiLCJleHAiOjE1NjQ0NTI2MjQsIm5iZiI6MCwiaWF0IjoxNTY0NDUyMzI0LCJpc3MiOiJodHRwczovLzEzNS4yNTEuMTA4LjU1L2F1dGgvcmVhbG1zL3JhYmJpdG1xYXV0aCIsImF1ZCI6InJh
YmJpdG1xLXJlc291cmNlIiwic3ViIjoiYTg5ODQzYWMtODI4Zi00YzRkLWE2NTYtNzA3ODA2NTZjYjJkIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicmFiYml0bXEtcmVzb3VyY2UiLCJhdXRoX3RpbWUiOjAsInNlc3
Npb25fc3RhdGUiOiIxNGIzNTY4NC0zNzBkLTRhNDEtODI3MC02MWUzYTljYTgyNGEiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwicmFiYml0bXF1c2VyIiwidW1h
X2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJhdXRob3
JpemF0aW9uIjp7InBlcm1pc3Npb25zIjpbeyJzY29wZXMiOlsicmFiYml0bXEtcmVzb3VyY2UtcmVhZCJdLCJyc2lkIjoiZTdmMTJlOTQtNGMzNC00M2Q4LWIyYjEtYzUxNmFmNjQ0Y2VlIiwicnNuYW1lIjoidmhv
c3QxIn0seyJyc2lkIjoiMTJhYzNkMWMtMjhjMi00NTIxLThlMzMtMDk1MmVmZjEwYmQ5IiwicnNuYW1lIjoiRGVmYXVsdCBSZXNvdXJjZSJ9XX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaW
VkIjpmYWxzZSwibmFtZSI6InRhbyB6b3UiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0YXpvdSIsImdpdmVuX25hbWUiOiJ0YW8iLCJmYW1pbHlfbmFtZSI6InpvdSIsImVtYWlsIjoidGFvLnpvdUBxcS5jb20ifQ.R
-1OjXJOfy-bYQC9lAHGtt3ErpLE0VPSPntqYG9NVP7CpzAIJlP9QRj7WmIKIcYQhZ5huZBkgLVwY2-fGahaWb-VOU1y1KLdLH60fBUSdhhyQphXKgg43NWpYVMVuIx_nbR-GKvBB7VwZcHvHxKXcHB--eK9YXxFZbf
dAyH-TMiPvejDbB1bPJj93uOxZ7okL-6eFW92ONJz4BK_ja5ifhLMt9MfyarJyswUec8T0T6S8w8OO-x3VGnQYHiMuQhJ_arhwJLMzGc-9BMopeRmR-tQzNqDPtbHbbZq3or_jMssUgf5hv0QqP1OIGMuxSIypaqG4
ShRxcPEZXIwxFqeHg'
password=r"#{'password'=>%s}" %(token)
credentials = pika.PlainCredentials('tazou', password)
parameters = pika.ConnectionParameters('localhost',
                                       5672,
                                       'hosttest1',
                                       credentials)

connection = pika.BlockingConnection(parameters)
channel = connection.channel()
channel.queue_declare(queue='email',  durable=True)
channel.basic_publish(exchange='',
                      routing_key='email',
                      body='Hello World!')
print(" [x] Sent 'Hello World!'")
connection.close()
```
my rabbitmq advanced.config likes:
```
[
  {rabbit, [
    {auth_backends, [rabbit_auth_backend_oauth2 ]}
  ]},
  {rabbitmq_auth_backend_oauth2, [
    {resource_server_id, <<"rabbitmq">>},
    {key_config, [
      {default_key, <<"legacy-token-key">>},
      {signing_keys,
        #{<<"legacy-token-key">> => {pem, <<"-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyUiG/nOwpcL1PBio0djkV2mqgowKcgmMcLVupLZn/Gzf1kpT1ftbA2wOArSuC/aIriRwBVdHK43+Pr6+FiKJNEusfo2E/gYimE4eHuaeL07wFT0USaOToL
2R44L7Z6zXh2MWPtSrN2S20kiVErlp6kJwwbtRKY2xc7KlMhM4JLNiaueCirWVzdJ0ZbuLBAFPPO4yzjXkb4eRBE7+eayUHtYyA3DHu/T8VlaH5V40e/MCQEmb0kqs/v0veDwxGimWoEgJ9Bf019fVGk7p8fKdgeJF
jRPRrZoN4YfJWsYY8kv+LGM73aKEFK+sXMTtrtUn9umH+1yGhaymthk6BUoH+QIDAQAB
-----END PUBLIC KEY-----">>}
         }
      }]
    }
  ]}
].

```
the server reported the log:

```
2019-07-30 06:27:08.504 [warning] <0.1299.0> HTTP access denied: Authentication using an OAuth 2/JWT token failed: {error,
                                                   {invalid_token,error,
                                                    {badarg,[<<"admin">>]},
                                                    [{jose_jws,do_expand,1,
                                                      [{file,
                                                        "src/jose_jws.erl"},
                                                       {line,463}]},
                                                     {jose_jws,expand,1,
                                                      [{file,
                                                        "src/jose_jws.erl"},
                                                       {line,176}]},
                                                     {jose_jws,
                                                      peek_protected,1,
                                                      [{file,
                                                        "src/jose_jws.erl"},
                                                       {line,232}]},
                                                     {jose_jwt,
                                                      peek_protected,1,
                                                      [{file,
                                                        "src/jose_jwt.erl"},
                                                       {line,162}]},
                                                     {uaa_jwt_jwt,get_key_id,
                                                      1,
                                                      [{file,
                                                        "src/uaa_jwt_jwt.erl"},
                                                       {line,28}]},
                                                     {uaa_jwt,
                                                      decode_and_verify,1,
                                                      [{file,
                                                        "src/uaa_jwt.erl"},
                                                       {line,48}]},
                                                     {rabbit_auth_backend_oauth2,
                                                      check_token,1,
                                                      [{file,
                                                        "src/rabbit_auth_backend_oauth2.erl"},
                                                       {line,110}]},
                                                     {rabbit_auth_backend_oauth2,
                                                      user_login_authentication,
                                                      2,
                                                      [{file,
                                                        "src/rabbit_auth_backend_oauth2.erl"},
                                                       {line,45}]}]}}
```
the error was reported by the token can't be split into three parts.
as i check the code, the user_login_authentication will transform the password field to map and get the password.
I'm not sure what's the content should be filled in the client code. Should i use external mechinism instead of plain?
I'm new to erlang and rabbitmq. any suggestions will be appreciated.

B.R,
Tao

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This plugin [targets RabbitMQ 3.8](https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2#supported-rabbitmq-versions). It depends on internal interface changes that were not backported and at this point in the `3.7.x` cycle, never will be. You can use the latest 3.8 beta, IIRC it already includes this plugin in the distribution.

I haven't followed Pika 1.0+ API changes in this area closely but the token must be specified in the password field. The username will be ignored. The line that fills the JWT into a raw literal of `"#{'password'=>%s}"` seems rather unusual to me. It is not what [modern Pika examples](PlainCredentials) use, for instance.

No, `EXTERNAL` authentication mechanism must not be used since you *are* authenticating using credentials, they just come in a form of a JWT. `EXTERNAL` is appropriate when authentication is performed using TLS peer verification or similar, so, a mechanism that does not depend on a pair of credentials coming from the client.

**Comment by taijitao** [comment]
Thanks for your reply. 
I tried first that only included token in code, but it doesn't work.
```
token=b‘...’
credentials = pika.PlainCredentials('tazou', token)
```
after checking the code,  i just tried that abnormal way. 
I'll try rabbitmq 3.8 and input the token directly.
if i want to use the rabbitmq 3.7.x(i don't know when 3.8 will be released), should I change the plugin?

**Comment by michaelklishin** [comment]
There is no alternative for 3.7.

**Comment by taijitao** [comment]
sorry to bother you.
I'm not sure when the rabbitmq 3.8 will be released. Do you know when it will be released?
so if i wanna to use 3.7.x to meet the target goal. Is it possible for me to change the plugin to meet the 3.7?
As you said, this plugin uses interface only in 3.8.
i don't know what's the gap. It seems you only use the common authen/author interface.
do you mean with the 3.7.x interface, there is no way to provide oauth2 validation?
hope you could give me some detail when you're available.

**Comment by michaelklishin** [comment]
Our team does not use GitHub issues for questions and discussions.

RabbitMQ 3.8 will be released in the next few months. We are fairly confident that the beta versions are quite stable and early adopters should not run into any major issues. If you really need one of the new features in 3.8, I'd consider starting with beta releases.

This plugin depends on internal `authn` and `authz` changes in RabbitMQ server. They were necessary so that authorization operations have access to the password (in 3.7 they don't, as other backends do not need it). This in turn lets you specify the token in the password field. Early versions of this plugin used the username for that but that value is logged in many cases, and since tokens are sensitive values, this was only acceptable for a prototype.
Modifying the plugin will not make it 3.7 compatible. You have to modify RabbitMQ itself.

I'd recommend either not using the plugin or adopting a 3.8 beta. A first 3.8 RC is expected next month.

**Comment by taijitao** [comment]
Got it. Thanks a lot.
