### ISSUE TITLE
uaa_jwt binaries

### ISSUE THREAD

**Issue by justinteaw** [rabbitmq/rabbitmq-auth-backend-uaa#9]
I would like to try this plugin and I found the zip you provided here:
https://github.com/rabbitmq/rabbitmq-auth-backend-uaa/issues/7

when i try to enable the plugin, it mentions it needs the [uaa_jwt] plugin.  Can you please provide the .ez file? 

thanks.

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by justinteaw** [comment]
Thanks, I added a post.  But do you mind at least to put all the compiled
binaries (ez files) in github so we don't have to bother you with these
types of questions?

**Comment by michaelklishin** [comment]
@justinteaw I will upload two `.ez` files in a bit but there is a reason why this project is listed as experimental and [one of the dependencies](https://github.com/rabbitmq/uaa_jwt) wasn't even open source just a few minutes ago: it's not ready for prime time.

Unless you are willing to build it from source, target RabbitMQ 3.7.0 and generally follow its development, this plugin is not yet ready for you (and potentially never will be).

**Comment by michaelklishin** [comment]
[rabbitmq-users thread](https://groups.google.com/forum/#!topic/rabbitmq-users/Q0DwZyzZrC8).

I'm attaching the same set of files here but please see the thread as there are important details around OAuth 2 support in RabbitMQ that are not discussed publicly very often.

[rabbitmq_auth_backend_uaa-9220c46-with-deps.zip](https://github.com/rabbitmq/rabbitmq-auth-backend-uaa/files/1297007/rabbitmq_auth_backend_uaa-9220c46-with-deps.zip)
